---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
  labels:
    name: nginx-test-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

...
